import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import NavigationWrapper from "@/components/Layout/NavigationWrapper";

export const metadata: Metadata = {
    title: "Quantech",
    description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{children: React.ReactNode }>) => {
    return (
        <html lang="en">
            <body className={``}>
                <NavigationWrapper>
                    <main id="main" className="bg-zinc-800 min-h-screen">
                        {children}
                    </main>
                </NavigationWrapper>
                <Footer />
            </body>
        </html>
    );
};

export default RootLayout;