import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Quantech",
  description: "Generated by create next app",
};


const RootLayout = ( { children }: Readonly<{children: React.ReactNode }> ) => {
    
    return (
        <html lang="en">
            <body
                className={``}
            >
                <Nav />
                {children}
                <Footer />
            </body>
        </html>
    )
}

export default RootLayout